apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: portfolio-build
  labels:
    app: portfolio
    app.kubernetes.io/component: portfolio
    app.kubernetes.io/instance: portfolio
    app.kubernetes.io/name: portfolio
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: portfolio:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/splax-s/splax-portfolio.git
      ref: main
    type: Git
    contextDir: ""
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openshift
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: portfolio-webhook-secret
  - imageChange: {}
    type: ImageChange
