apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: portfolio-openshift

resources:
- imagestream.yaml
- buildconfig.yaml
- deployment.yaml
- service.yaml
- route.yaml

commonLabels:
  app: portfolio
  version: v1.0.0
  environment: production

namespace: portfolio

images:
- name: portfolio
  newTag: latest

replicas:
- name: portfolio
  count: 1

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: portfolio
  spec:
    template:
      spec:
        containers:
        - name: portfolio
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
