apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio-dev

resources:
- ../../

commonLabels:
  environment: development

patchesStrategicMerge:
- deployment-patch.yaml
- route-patch.yaml

replicas:
- name: portfolio
  count: 1
