apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio-prod

resources:
- ../../

commonLabels:
  environment: production

patchesStrategicMerge:
- deployment-patch.yaml
- route-patch.yaml

replicas:
- name: portfolio
  count: 3
